### ISSUE TITLE
Cannot delete all records in a many-to-many

### ISSUE THREAD

**Issue by far-blue** [atlasphp/Atlas.Orm#105]
Hi all,

I'm trying to delete all relations in a many-to-many relationship and it's not working for me - no DELETE sql statement is executed.

I have a many-to-many relationship between A and C via B. On A, if I set a new non-empty RecordSet on A->C then it works fine and records in B are deleted and created as expected. 

However, if I set an empty RecordSet on A->C, or if I call A->C->detachAll() or if I set A->C = null then no DELETE sql is issued.

I've also tried the same actions on the A->B RecordSet with the same result.

Is this a bug or am I doing something wrong?

In all cases I'm calling A->persist().

**Comment by far-blue** [comment]
anyone have any thoughts on this?

**Comment by jakejohns** [comment]
@far-blue i posted #107 which may be related. I am also confused.

**Comment by jakejohns** [comment]
@far-blue See https://github.com/atlasphp/Atlas.Mapper/pull/16

Workaround example, given many-to-many between `post` and `category` via `post_category`:
```php
foreach ($post->post_category as $through) {
    $through->setDelete(true);
}
$post->categories->detachAll();
//...
$atlas->persist($post);
```

**Comment by far-blue** [comment]
thanks for the suggestion and the PR :) Hopefully it will be accepted :)
