### ISSUE TITLE
Help: how to use advanced ORM feature

### ISSUE THREAD

**Issue by smagnaschi** [atlasphp/Atlas.Orm#111]
I have some questions regarding the use of the ORM. I read the docs but I can't seem to find a solution, hope someone could help me. Thanks in advance.

## Scopes

Let's say that I have a generic table `photo_galleries` in my database with different fields. This table populates photo galleries for different websites. `lang` and `valid` are two of those fields.

Is there a way to define at the `PhotoGallery` class level some scopes that will be applied on all the following queries?

Such as:

- `(lang = 'it_IT' and valid = true)` for the italian website
- `(lang = 'en_EN' and valid = true)` for the english website
- no default scope for the administrator panel that needs to access all the photo galleries

Right now the only way I've found is to store somewhere the conditions (let's say in a class constant) and put them as the second parameter in the $atlasOrm->select() method, but I imagine there should be some better way to do this to handle it better.

## Related to the above

Is it possible to create child classes such as PhotoGalleryItalian PhotoGalleryEnglish PhotoGalleryAdmin that could be used directly and would have the scope applied?

## Relationship, limit and order

Let's take the example above with `photo_galleries`. This table is mapped to the `photos` table with a many to many relationship through an intermediate table `photo_gallery_items` that also has a field that gives the photo an order. I can model the base relationship correctly and I can fetch all the photos for a single gallery. 

But:

- how can I model the relationship such as the photos fetched would be ordered through the `order` field in the `photo_gallery_items` (so that I'll have the photos ordered correctly). 

Working with callables like the following seem to work

```php
    $orm
        ->select(\App\DataSource\PhotoGallery\PhotoGallery::class)
        ->with([
            'photo_gallery_items' => function($sub) {
                return $sub->with(['photos'])->orderBy('`order` ASC');
            }
        ])
        ->fetchRecordSet()
```

but I'm wondering if it's the idiomatic approach.

- how can I limit the elements coming through the relationship when fetching entire recordsets (say that I want to fetch the first photo of the set to use as the cover)?

This won't work because it will limit the entire subquery.

```php
    $orm
        ->select(\App\DataSource\PhotoGallery\PhotoGallery::class)
        ->with([
            'photo_gallery_items' => function($sub) {
                return $sub->with(['photos'])->orderBy('`order` ASC')->limit(1);
            }
        ])
        ->fetchRecordSet()
```

# Column renaming

We have a very legacy database with mixed language columns and we want to bring it to a common english standard. Is there a way to alias one or more columns in the class model so that we can reference the alias in code rather than the actual column name? In this way I could reference `$photoRecord->additional_info` and that field would be mapped to the `InformazioniAddizionali` column in the database. Both for reads and writes.

Thanks

**Comment by pmjones** [comment]
Hi @smagnaschi,

Many questions! I'll try to respond to them separately.

> Is there a way to define at the PhotoGallery class level some scopes that will be applied on all the following queries?

My first inclination is to point you to the "Events" classes: [Table Events](http://atlasphp.io/cassini/table/events.html) and [Mapper Events](http://atlasphp.io/cassini/orm/events.html). My guess is that you want to work with the PhotoGalleryTableEvents::modifySelect() method, and add a WHERE clause to all SELECT queries.

**Comment by pmjones** [comment]
RE subqueries as callables:

> I'm wondering if it's the idiomatic approach.

Yes, it is the idiomatic approach; it's the *only* approach, really, if you are trying to do it all in a single fetch() call. Cf. http://atlasphp.io/cassini/orm/reading.html#1-1-3-4-1

**Comment by pmjones** [comment]
RE aliased column names:

>  Is there a way to alias one or more columns in the class model so that we can reference the alias in code rather than the actual column name?

The first thing I can think of is, in your Record classes, override __get() and __set() to intercept the aliases. For example:

```php
    public function __get($field)
    {
        $alias = [
            'additional_info' => 'InformazioniAddizionali',
        ];

        $field = $alias[$field] ?? $field;

        return parent::__get($field);
    }

    public function __set($field, $value)
    {
        $alias = [
            'additional_info' => 'InformazioniAddizionali',
        ];

        $field = $alias[$field] ?? $field;

        parent::__set($field, $value);
    }
```

But do note that it will work only on the Record class; you will still have to reference the actual column name in any queries.

**Comment by pmjones** [comment]
Finally:

> how can I limit the elements coming through the relationship when fetching entire recordsets (say that I want to fetch the first photo of the set to use as the cover)?

This is the hardest question of the bunch. The way to answer it is to ask this question: how would you write the plain SQL to do that? The answer to *that* question is: I don't think you can. That means you need to try another approach.

I have been in a similar situation, and the solution was to add a column to indicate which row of each set should be considered first in the collection, then add a query condition on that value. 

You might even do so in a custom relationship. It's hard for me to give an example without knowing your schema, but here's one attempt:

```php
class PhotoGalleryItemsRelationships extends MapperRelationships
{
    protected function define()
    {
        $this->manyToOne('cover_photo', PhotoGallery::CLASS)
            ->where('is_cover_photo = 1');
    }
}
```

Maybe that will give you some ideas.

**Comment by pmjones** [comment]
Let me know if you need anything else related to this!
