### ISSUE TITLE
Help: Only the first result in a select includes data from related records

### ISSUE THREAD

**Issue by Rockburner** [atlasphp/Atlas.Orm#112]
I have a relational database, accessed via Atlas, and I'm getting a very strange bug where only the first record from a select query is returned with relational information.  I'm not sure if this is unique or I simply cannot find a similar issue with a fix. (despite trying).
eg:
```
$fetch = $atlas->select(Table1::class);
$fetch->columns("table1.*");
$fetch->with([
          'table2relationship'=>[
                'table3relationship'
            ]
        ]);
$fetch->fetchRecords();
```
returns:
```
Array
        (
            [0] => stdClass Object
                (
                    [id] => 16
                    [int_1] => 58
                    [table2_id] => 332
                    [text] => asdf
                    [created] => 
                    [table2relationship] => stdClass Object
                        (
                            [id] => 332
                            [int_1] => 7166
                            [table3_id] => 1
                            [created] => 2019-08-16 15:12:21
                            [modified] => 2019-12-12 08:20:48
                            [table3relationship] => stdClass Object
                                (
                                    [id] => 1
                                    [string] => STRING
                                )

                        )

                )

            [1] => stdClass Object
                (
                    [id] => 2
                    [int_1] => 58
                    [table2_id] => 332
                    [comment] => test
                    [created] => 2020-01-20 14:08:07
                    [table2relationship] => 
                )

            [2] => stdClass Object
                (
                    [id] => 1
                    [int_1] => 58
                    [table2_id] => 332
                    [text] => test
                    [created] => 2020-01-20 13:16:11
                    [table2relationship] => 
                )

        )
```
I have setup the relationships thus:
```
class Table1Relationships extends MapperRelationships
{
    protected function define()
    {
        $this->oneToOne('table2relationship', Table2::class, ['table2_id'=>'id']);

    }
}
```
and
```
class Table2Relationships extends MapperRelationships
{
    protected function define()
    {
        $this->oneToOne('table3relationship', Table3::class, ['table3_id'=>'id']);

    }
}
```

Is this a bug in the ORM, perhaps a repeat query is not repeated because it would be duplication of effort and the results are not passed on to the next iteration?  or a configuration error in the MapperRelationship classes?

**Comment by Rockburner** [comment]
Just to update on this - I believe what is happening is that any 'duplicated' queries (eg where the table2.id is the same) are not being run, obviously to prevent duplication of effort, however the results from first iteration of that duplicated query are not being applied to the second, third etc objects in the primary results array.
I've worked around this for my current project with a simple loop of the affected results array which populates and then draws from a secondary array of the subsidiary data objects.:
```
$table2relationships = array();

foreach($results AS $i=>$result){
    if(!empty($result->table2relationship)) {
        $table2relationships [$result->table2_id] = $result->table2relationship;
    }
    else {
        $result->table2relationship = $table2relationships [$result->table2_id];
    }
}
```
Not the best option for large results sets (looping the whole result set takes time that shouldn't be wasted), but it serves the purpose for the time being.
Hopefully this might help someone else if anyone gets the same issue?

FWIW this is in Atlas ORM v3.

**Comment by pmjones** [comment]
@far-blue Do you think this has anything to do with <https://github.com/atlasphp/Atlas.Mapper/pull/13> ?

**Comment by pmjones** [comment]
@Rockburner thanks for the report, and sorry for the hassle -- keep the info coming, and we'll try to figure it out.

**Comment by pmjones** [comment]
@Rockburner try this Atlas.Mapper branch in your installation https://github.com/atlasphp/Atlas.Mapper/tree/revert-13-stitch_optimisations and let me know if the problem disappears.

**Comment by pmjones** [comment]
@Rockburner another idea -- how is the relationship defined? It looks like you have many different table1 records related to one table2 record, in which case it should be a many-to-one.

**Comment by Rockburner** [comment]
@pmjones I'll look into those suggestions, many thanks.

**Comment by Rockburner** [comment]
@pmjones ManyToOne appears to have been the key mistake on my part!
Many thanks for the assist!
