### ISSUE TITLE
[Help Required] Getting Atlas\Mapper\Exception when trying to fetch a record from SQLite

### ISSUE THREAD

**Issue by sebastianknopf** [atlasphp/Atlas.Orm#113]
I want to load data from a SQLite database using Atlas.Orm.

My atlas instance is created using this snippet
```
$builder = new \Atlas\Orm\AtlasBuilder([
       'sqlite:' . $databaseName
    ]);
$orm = $builder->newAtlas();
``` 

Afterwards I created all skeleton classes from my database, which worked fine. But if I want to fetch some data, I get the exception **Data\Stop\StopMapper not found in mapper locator.** I'm using this snippet for fetching my data:
```
$result = $orm->select(Stop::class)->fetchRecords();
```

What am I doing wrong here? I assume, I must register the mapper in the mapper locator before, but I cannot find anything about that in documentation.

Regards
Sebastian

**Comment by sebastianknopf** [comment]
Okay, sorry for that, it was definitely my fault! I got into trouble with composer psr-4 autoloaders... Sorry!

**Comment by pmjones** [comment]
Glad it worked itself out!

**Comment by gcx3829** [comment]
Hi @sebastianknopf , I came across the same problem. How do you fix it?
