### ISSUE TITLE
patch(record, data) or merge(record, data) + events

### ISSUE THREAD

**Issue by yespire** [atlasphp/Atlas.Orm#12]
Hi Paul,

in apps, there are normally 2 types of updates:
1. explicit fields update
   $user->name = "joe doe";
   $atlas->update($user);
2. implicit / fuzzy fields update
   $atlas->patch($user, $data);
   $atlas->update($user);

I think the patch probably should have some MapperEvents methods, but no need for TableEvents methods, any thought ?

**Comment by pmjones** [comment]
Is this pretty much the same question as #16?

**Comment by yespire** [comment]
This was intended as a question for consideration of adding patch-related-events. I will close this.

**Comment by pmjones** [comment]
Gotcha; thanks.
