### ISSUE TITLE
suggestion: variable naming and meaning suggestion

### ISSUE THREAD

**Issue by yespire** [atlasphp/Atlas.Orm#17]
@pmjones @harikt 

Just a suggestion / idea about variable naming
Assuming we have users table with fields -- id, name, status

$colsVals = [ 'name' => 'Joe Doe', 'status' => 'active' ]
--- assoc array
-- at application level, we normally use $post, $data, $config to imply assoc data array

$cols = [ name, status ]
--- numeric array

$vals = [ 'joe doe', 'active' ]
--- numeric array

$colsMeta / $colsSchema / $colsDetails = [ ... ]
--- array of arrays
--- the array result produced by SHOW COLUMNS FROM users-table

Extra Notes:
--- $cols is sometimes used to represent $colsVals + $colsMeta
--- $colsVals are mostly consistent already

**Comment by pmjones** [comment]
I agree with your assessment, $colsVals is not a good enough name. I have replaced it internally with $whereEquals instead; as in, "where $key equals $val."
