### ISSUE TITLE
Idea: Row::$pseudo

### ISSUE THREAD

**Issue by yespire** [atlasphp/Atlas.Orm#18]
@pmjones @harikt 

this is related to row/record property value assignment
the idea is that, we CAN allow user to add additional properties

$user->full_name = $user->first_name .' '. $user->last_name;   // assume full_name is not a field

we can check against "cols" + "related", on miss, we add the full_name to "pseudo" data array

**Comment by pmjones** [comment]
> we can check against "cols" + "related", on miss, we add the full_name to "pseudo" data array

I struggled with this a bit myself when working through the initial versions of Atlas. What I came to was this: Atlas is for the _persistence_ model. If a field is not part of the data being _persisted_, then, what place does it have in the _persistence_ model? As such, I think "pseudo fields" belong in the domain model, not in the persistence model.
