### ISSUE TITLE
Idea: Connection configuration on table level

### ISSUE THREAD

**Issue by yespire** [atlasphp/Atlas.Orm#22]
@pmjones @harikt 

just an idea
we don't have a project with enough load to justify such feature.
however it is reasonable design concern when a project producer chooses ORM library that can distributing database load

IF a site become busy, it will need:
1. split some tables into a different servers, for example
   -- sessions table if session is implemented with database
   -- i think the best place is to have getConnection() inside each table, when missing, it will fall back to default
2. split read and write connection, so each table may also need getReadConnection, getWriteConnection

---

The idea would be that when a project needs to move for example sessions table to a different host, it would add the following:

```
SessionTable {
     public function getConnectionName() {
          return 'new-host-connection';  // as "key" for $connectionLocator
    }
}
```

**Comment by yespire** [comment]
Counter argument to my idea:
1. Atlas wants to be minimalistic
2. table without connection info can be advantageous as well, for example, we can create multiple entity-manager classes, each ties to a different database connection.
   this way, same Record/Entity can be used with multiple connections at the same time

a more specific use case is this -- let's say we have a reference table needs to be update from stage db to live database, we can have:
$record = $stage_entity_manager -> fetchRecord('RefRecord', 123);
$live_entity_manager->persist($record);

**Comment by harikt** [comment]
This feature can be implemented with adding 2 things in the `Atlas\Orm\Table\AbstractTable` 
1. protected $read_connection;
2. protected $write_connection;

and use `$this->read_connection` inside `getReadConnection` , `getRead` method.
