### ISSUE TITLE
Best way to handle sorting?

### ISSUE THREAD

**Issue by andrewshell** [atlasphp/Atlas.Orm#29]
I'm working on a site that has a very complex interrelated database structure.

https://github.com/andrewshell/pen-paper-2/tree/0.1.0

Here is the most complex query in my application:
[CreatorsAtlasRepository::getCreatorById](https://github.com/andrewshell/pen-paper-2/blob/0.1.0/src/Persistence/CreatorsAtlasRepository.php#L33-L127)

Here is an example of one of the relationships.

```
Creator─RpgBookCreator─┬─RpgBook─┬─Publisher
                       │         │
                       │         └─GameLine
                       │
                       └─Credit
```

Ideally, I'd sort the RpgBookCreators by RpgBook.title but from what I can tell, there is no easy way of doing that through the API.

My solution was to `getArrayCopy` and then run the result through a series of usorts.

I'm wondering if there is a better way to handle these sorts or if what I'm doing is the best practice at this time.

**Comment by pmjones** [comment]
I suppose the easiest way to figure it out would be to ask: "How would one sort that result set in plain old SQL?"

**Comment by andrewshell** [comment]
In plain old SQL, I'd do a query for each of the creators. So for RpgBookCreator it would be:

``` sql
SELECT
    *
FROM
    `rpg_book_creators` rbc
INNER JOIN
    `rpg_books` rb ON rbc.`rpg_book_id` = rb.`rpg_book_id`
INNER JOIN
    `publishers` p ON rb.`publisher_id` = p.`publisher_id`
INNER JOIN
    `game_lines` gl ON rb.`game_line_id` = gl.`game_line_id`
INNER JOIN
    `credits` c ON rbc.`credit_id` = c.`credit_id`
WHERE
    rbc.`creator_id` = 2
ORDER BY
    rb.`title`
```

But from what I understand of Atlas, it doesn't do joins, rather it does a query for each table then stitches the results together.

**Comment by pmjones** [comment]
Are all those 1:1 relationships? That is, would `rbc` columns be duplicated from row to row here?

**Comment by andrewshell** [comment]
Everything would be 1:1 except if a creator has multiple credits for a book.  However, both the original site and my first stab at it would just show the book multiple times.  I later wrote a post-processor that merged the credits. 

The most number of credits for a single creator is 8 however 87% only have one credit and 10% have 2 credits.

**Comment by pmjones** [comment]
/me nods

In theory, you should be able to change from `$atlas->fetchRecords(...)` to `$atlas->select(...)->fetchRecords()`, add a join of your own on that master select, and then order by it. As long as you don't select any joined columns, you should not get any repeated rows in that master set.

This reminds me that I wanted to add a "joinWith($relation_name)" on the MapperSelect class.

**Comment by pmjones** [comment]
I think I have a solution in place for this now in the 1.x branch.

In your master select, you can now call `innerJoinWith($relatedName)` and then use the $relatedName as an alias in where, order, etc.  Given your SQL example above:

```
$recordSet = $atlas->select(RpgBookCreators::CLASS)
    ->distinct()
    ->innerJoinWith("rpg_books")
    ->orderBy("rpg_books.creator_id")
    ->with([...])
    ->fetchRecordSet();
```

The "innerJoinWith()" adds a join to the master select, aliasing the real table name for the relationship as the related name. It does not select columns at all, on purpose; you still need to add a with() call to get back the related records.

Even though no columns are selected, if there are rows in the foreign table, you will end up with duplicate rows in your native table, so you need to add the distinct() call to eliminate the duplicates. (I might make that a standard behavior later.)

You also have "leftJoinWith($relatedName)" and "joinWith($joinType, $relatedName)" available.

There is no way to join with a a join with right now, so you only have access to the master select's relationships.

Let me know if that helps!

**Comment by andrewshell** [comment]
Yeah, seems to work.

One thing is that I can't use distinct. If I do distinct and orderBy I get the following:

```
PDOException: SQLSTATE[HY000]: General error: 3065 Expression #1 of ORDER BY clause is not in SELECT list, references column 'pen-paper-2.rpg_book.copyright' which is not in SELECT list; this is incompatible with DISTINCT
```

However it doesn't look like distinct is needed because it's a manyToOne join so there are no duplicates.

Final code:

``` php
$entity['rpg_book_creators'] = $this->atlas
    ->select(
        RpgBookCreatorMapper::CLASS,
        [
            'creator_id' => $id,
        ]
    )
    ->innerJoinWith('rpg_book')
    ->orderBy([
        'rpg_book.copyright DESC',
        'rpg_book.title ASC',
    ])
    ->with([
        'rpg_book' => function ($book) {
            $book->with([
                'publisher',
                'game_line',
            ]);
        },
        'credit',
    ])
    ->fetchRecordSet()
    ->getArrayCopy();
```

**Comment by pmjones** [comment]
> it doesn't look like distinct is needed because it's a manyToOne join so there are no duplicates.

Thanks for pointing that out; it means I should either leave out auto-`distinct()` entirely from the joinWith() code, or at least check the relationship to see if it's to-many or to-one.

> Final code:

That is just gorgeous. :-)

As such, I'll close this as "solved". Please re-open if you feel it necessary. And thanks for the good reporting!
