### ISSUE TITLE
Question : Validation

### ISSUE THREAD

**Issue by harikt** [atlasphp/Atlas.Orm#36]
Hi Paul,

I noticed in your todo : 

```
- sanitize/validate Records and Rows -- as events
```

Probably I may be missing something. But I feel the current events don't check if they return true or false and always execute the remaining stuff. So I believe even if the validation fails it will insert / update / delete things. So the question is do we really need a good event handler like Aura.Signal here ?

The idea is to stop on failures completely.

**Comment by pmjones** [comment]
> The idea is to stop on failures completely.

Yes; I'm presuming "throw an exception" to do that. Needed especially inside a transaction.
