### ISSUE TITLE
Require PHP 7 ?

### ISSUE THREAD

**Issue by pmjones** [atlasphp/Atlas.Orm#47]
(Open discussion topic.)

I am preparing another alpha release of Atlas. Currently it requires PHP 5.6, and this upcoming alpha will continue with that requirement.

However, for the next release after that (whether alpha or beta), I think upgrading the requirement to PHP 7 will provide some advantages. Typehinting parameters and returns alone will be great.

Does anyone using Atlas have arguments against this?

**Comment by goetas** [comment]
I have the same issue with some libs I maintain... my question is even more specific... 7.0 or 7.1? 

Nullable types are a huge difference... I worked with some 7.0  projects, and type-hinting without nullability was really painful, so painful that upgrading to 7.1 was a "must" for me

**Comment by pmjones** [comment]
@goetas So it sounds like you are "yes" on PHP 7 overall, with a preference for 7.1 ... ?

**Comment by goetas** [comment]
@pmjones exactly.

The preference for 7.1 is a feeling I have. I would like to hear third opinions, in order to exchange feelings for reasons

**Comment by andrewshell** [comment]
I support 7.1 as a minimum version. All of my projects that use Atlas in are already 7.1 because as @goetas said: "type-hinting without nullability was really painful".

**Comment by Grummfy** [comment]
it's new so let's start to php7.1.

**Comment by goetas** [comment]
A thing to consider is that php 7.0 will stop receiving bugfixes in less that 8 months, while 7.1 will have about 19 months of bugfixes (http://php.net/supported-versions.php)

**Comment by koriym** [comment]
The latest php is necessary for those who use the latest framework / library :)

**Comment by goetas** [comment]
@pmjones looks that you have an anonymous verdict.... 

anybody with different opinions?

**Comment by pmjones** [comment]
@goetas I'm going to leave this open at least another day, but I don't expect objections.

**Comment by pmjones** [comment]
Folks, I have modified the plan. Next release will be stable. Then PHP 7 development can begin in a new 2.x branch.

(This is uncharacteristic for me. Normally I like lots of alphas, a couple betas, then a stable. Consider this as "Paul trying something new." ;-)

**Comment by pmjones** [comment]
All righty: Atlas ORM 1.0.0 stable is released, using PHP 5.6.  Next version will be minimum 7.1. Thanks everyone for your support!

**Comment by harikt** [comment]
> Consider this as "Paul trying something new." ;-)

Release early, release often. I hope this may be what "Paul trying something new." ;-) .
