### ISSUE TITLE
Creating new record with related

### ISSUE THREAD

**Issue by jelofson** [atlasphp/Atlas.Orm#55]
Consider the following:
I have a post mapper with a many to one relationship for the author. 
```php
$author = $atlas->fetchRecord(
    AuthorMapper::class,
    'juser'
);

$post = $atlas->newRecord(
    PostMapper::class,
    [
        'title' => 'New Post Title',
        'post'=>'Lorem ipsum dolar sit amet',
    ]
);
// Set the author related to an author record.
$post->author = $author;

// This fails as it doesn't set the foreign key to the primary key of the author record.
$success = $atlas->insert($post);

// However, this works fine
$post->author_id = $author->id;
$success = $atlas->insert($post);
```
Should scenario 1 work? IE, setting a related to the associated object directly.

The same holds true for updating a post record. IE setting the related author to a different author record.

Thanks.

**Comment by pmjones** [comment]
You have to update the IDs yourself.

Having said that, I wonder if you *should* have to. My original intent was for Atlas to what you tell it, and not much else. But this might well fall into one of the exceptions. I can see where the Mapper insert() and update() methods could inspect the Record and Relationships, then apply the foreign values to the native fields appropriately. (This seems like a corollary to the fact that the Table object sets the last-insert-id on the primary key column on Row objects after insert().)

@jelofson Any thoughts on that?

**Comment by pmjones** [comment]
@jelofson I have pushed an experimental branch https://github.com/atlasphp/Atlas.Orm/tree/fix-record-keys with this relevant commit https://github.com/atlasphp/Atlas.Orm/commit/55fffe352cc9f180230a270058881d3c62aa94c1

With that, Mapper insert() and update() should "fix" the appropriate native/foreign keys, when a related record is present. (Note that many-to-many does nothing, as it *should* be covered by the one-to-many and many-to-one parts of the relationship definitions.)

I have no tests for it yet; in the mean time, if you're available, please take a look and maybe try it out.

**Comment by pmjones** [comment]
@jelofson I have expanded on this greatly; a new persist() method will now save not only the main record, but all the relateds that are attached, including the many-to-one (belongs-to) and many-to-many (has-many-through) relateds. Please review at your convenience.

**Comment by jelofson** [comment]
@pmjones Perfect, I will try this today/

**Comment by pmjones** [comment]
@jelofson Sweet. Let me know how it goes, and what needs to be improved/addressed.

**Comment by jelofson** [comment]
@pmjones Ok, first test with a manyToOne (belongsTo). I think it's close.
First, I tested the `update()` method.

Consider the following:
Post Record  belongs to a User record (a User has many Posts)
```php
<?php
$post = $this->atlas->fetchRecord(Posts::class, 2, ['user']);
// $post->user->id = 1

// Get a different user (id 2)
$user = $this->atlas->fetchRecord(Users::class, 2);

// Assign this user to the post record
$post->user = $user;

// Update the post
$success = $this->atlas->update($post);
// $post now belongs to user id 2 (confirmed in DB)
// So this seems to work as expected noting I made no change to the user record itself.
```
Now the `persist()` method, to see if it works the same or is different. I set the post's user id back to 1

```php
<?php
$post = $this->atlas->fetchRecord(Posts::class, 2, ['user']);
// $post->user->id = 1

// Get a different user (id 2)
$user = $this->atlas->fetchRecord(Users::class, 2);

// Assign this user to the post record
$post->user = $user;

// Persist the post
$success = $this->atlas->persist($post);
// $success is true, but the user id for the Post record was not changed. It still belongs to user id 1
```

Now try altering the user record before assigning it to the post
```php
<?php
$post = $this->atlas->fetchRecord(Posts::class, 2, ['user']);
// $post->user->id = 1

// Get a different user (id 2)
$user = $this->atlas->fetchRecord(Users::class, 2);

// modify the user record
$user->fullname = "Homer Simpson";

// Assign this user to the post record
$post->user = $user;

// Persist the post
$success = $this->atlas->persist($post);
// $success is true, but the user id for the Post record was not changed. It still belongs to user id 1
// The User record's fullname WAS changed, however. Even though it technically doesn't own the post.
```
Now let's try modifying the post record before persist, forcing it to be "dirty".

```php
<?php
$post = $this->atlas->fetchRecord(Posts::class, 2, ['user']);
// $post->user->id = 1

// Get a different user (id 2)
$user = $this->atlas->fetchRecord(Users::class, 2);

// Assign this user to the post record
$post->user = $user;

// modify the Post record
$post->title = "Tofino, BC is a nice place to visit";

// Persist the post
$success = $this->atlas->persist($post);
// $success is true AND the user id for the post record has also changed, 
//along with the modified title.
```

The last test, which I will only describe, was the same as test one. Using the `update()` method, but making a change to the user record before the update. As expected, the user record is not changed, as that is left to the work of the new `persist()` method. 

So, with `persist()` it seems as though the foreign key was only modified if the record had changed. It did not detect setting a different user record as a change. 

What do you think? Are those tests useful? 

I will try to get to the other relationships today too, if possible.

**Comment by pmjones** [comment]
The tests are *very* useful. Keep them coming. I will investigate in the mean time. Many thanks!

**Comment by pmjones** [comment]
@jelofson I have an intuition. In AbstractMapper::persist(), change ...

```php
        $method = $record->getPersistMethod();
        if ($method) {
            $this->$method($record);
        }
```

... to ...

```php
        $method = $record->getPersistMethod();
        if ($method) {
            $this->$method($record);
        } else {
            $this->fixNativeRecordKeys($record);
            $this->fixForeignRecordKeys($record);
        }
```

... and let me know if that fixes it for you.

**Comment by jelofson** [comment]
@pmjones Not quite (btw should be $this->relationships->fix...):
```php
        $method = $record->getPersistMethod();
        if ($method) {
            $this->$method($record);
        } else {
            $this->relationships->fixNativeRecordKeys($record);
            $this->relationships->fixForeignRecordKeys($record);
        }
```
While this does set the native record's keys correctly, the persist method is null, so it doesn't seem to do anything after fixing the keys. There is no call to `update()` the native record.  It only persists the foreign records. 

When altering only a related on an existing record, the row should be marked as MODIFIED to trigger and update. 
Remember, it worked correctly if I changed the post title in addition to the user. That marked the row as modified, which worked without the change you suggest above.

**Comment by jelofson** [comment]
@pmjones 
So, this works, but I haven't get determined if there would be negative consequences.

```php
        // in AbstractMapper::persist()

        $this->relationships->persistBeforeNative($record, $tracker);
        // fix native record keys
        $this->relationships->fixNativeRecordKeys($record);

        $method = $record->getPersistMethod();
        if ($method) {
            $this->$method($record);
        }
```
Not sure if you need to also call `$this->relationships->fixForeignRecordKeys($record);` as well.

**Comment by pmjones** [comment]
@jelofson Funny, I would have thought the `else` would catch it. Yeah, try adding fixForeignRecordKeys after the if $method block.

**Comment by pmjones** [comment]
Also, make sure you pull the latest version of the branch -- I moved some stuff around in update() that might affect your testing.

**Comment by pmjones** [comment]
@jelofson Also, make sure you pull the latest version of the branch -- I moved some stuff around in update() that might affect your testing.

**Comment by jelofson** [comment]
@pmjones Yup, latest version of the branch. Just double checked. 

Adding `$this->relationships->fixNativeRecordKeys($record);` to the `else` block does set the user id on the native record, however; the persist method will still be `null`. Therefore, the record remains unchanged. Of course, calling `update()` directly does work.

Here is what I think occurs:

You grab a post record and the related user record.
You grab a different user record and assign that to the post record
`$post->user = $user;`
You make no other modifications to the columns of the post record.
You call `$atlas->persist($post);` 
In the `AbstractMapper::persist()` method, `$record->getPersistMethod()` will return `null` as the row hasn't actually changed. Only the related changed. No update will be called on the post record. 

On the other hand, if you modify a column of the post record, then the row status is MODIFIED (via `Row::__set()` and `Row::modify()` and `$record->getPersistMethod()` returns as much. Therefore, an update is called on the native post record.

So, I think calling `$this->relationships->fixNativeRecordKeys($record);` needs to happen before the 
```
       $method = $record->getPersistMethod();
        if ($method) {
            $this->$method($record);
        }...
```
To ensure the native record (post) is properly marked as "dirty" (row status MODIFIED) and properly updated. 

Does that make any sense whatsoever? Is my understanding of what goes on under the hood correct?

**Comment by pmjones** [comment]
> Adding $this->relationships->fixNativeRecordKeys($record); to the else block does set the user id on the native record, however; the persist method will still be null. Therefore, the record remains unchanged. 

Oh, of course! (/me smacks forehead) Thanks a ton for that.

Gimme a few minutes, I'll change the persist() method a bit and you can tell me if it works.

**Comment by pmjones** [comment]
@jelofson All righty then -- pull the newest commit, and let me know how that works for you.

At the end of this, I'd love to see your tests in the repo, if you can pass them along.

**Comment by jelofson** [comment]
@pmjones Ok, pulled latest and on first quick check, we have success. Let me have at it a bit more once I get to the office and I will get back to you.

**Comment by pmjones** [comment]
@jelofson Ehhxcellent.

**Comment by jelofson** [comment]
@pmjones So here is my feedback after the latest testing. Thanks for your patience while I go through this.

As I mentioned, it looks like the oneToMany and manyToOne are working exactly as I expect them to.
Here is what I have experimented with:

```php
$post = $this->atlas->fetchRecord(Posts::class, 2);
$user = $this->atlas->fetchRecord(Users::class, 3);
$post->user = $user;
$success = $this->atlas->persist($post);
```
That works perfectly. I also appreciate that if the updating of the post fails, nothing happens with $user. Transactional goodness. 


```php
$post = $this->atlas->fetchRecord(Posts::class, 2);
$user = $this->atlas->newRecord(
    Users::class,
    [
        'fullname' => 'Sterling Archer'
    ]
);
$post->user = $user;
$success = $this->atlas->persist($post);
```
Again, this works as expected. The new user is added and the post updated. Yay!

```php
$user = $this->atlas->fetchRecord(Users::class, 1, ['posts']);
$post = $this->atlas->newRecord(
    Posts::class,
    [
        'title' => 'Lorem ipsum',
        'post' => 'Whatsoever things are true',
    ]
);
// Had to figure this out. If the user has no posts, you must create a new record set explicitly. 
if (! $user->posts) {
    $user->posts = $this->atlas->newRecordSet(Posts::class);
}
        
$user->posts[] = $post;
$success = $this->atlas->persist($user);
```
This worked perfectly.

---------------------------

Now on to the oneToOne. 

I set up a profiles table with a foreign key column `userid`, relating back to the users table. One user can only have one profile and vise versa. 

```php
$user = $this->atlas->fetchRecord(Users::class, 3, ['profile']);
$profile = $this->atlas->newRecord(
    Profiles::class,
    [
        'education' => 'Trump U',
    ]
);

$user->profile = $profile;
$success = $this->atlas->persist($user);
```
That works correctly. And this is probably the typical scenario in a oneToOne.

```php
$profile = $this->atlas->fetchRecord(Profiles::class, 1);

$user = $this->atlas->newRecord(
    Users::class,
    [
        'fullname' => 'Cat Stevens',
    ]
);

$profile->user = $user;

var_dump($this->atlas->persist($profile));
echo $this->atlas->getException();
```
A bit of a `covfefe` arises here. This give a bool true, and the new user is inserted, but not attached to the `$profile`. The profile remains unchanged. I haven't gone digging on this one yet. 

```php
$profile = $this->atlas->fetchRecord(Profiles::class, 1);
$user = $this->atlas->fetchRecord(Users::class, 2);
$profile->user = $user;

var_dump($this->atlas->persist($profile));
echo $this->atlas->getException();
```
Here, we get an exception.
`bool(false) Atlas\Orm\Exception: Primary key value for 'id' changed from '2' to '3'.`
In the OneToOne relationship, the `fixForeignRecordKeys()` is called and tries to modify the `getOn()` fields. This should only occur on the other side of the relationship (profile). Not sure how to fix this. This is probably an odd use case...

--------

Well, that's what I know so far. I hope implementing these methods isn't too much of a PITA. I do think they are worth having. You've gone at least one step beyond what I was hoping for, so thanks for that.

I will keep digging and see if anything jumps out at me. I still haven't messed with manyToMany yet. 

Oh, and I will happy to help write proper tests for the repo. Or at least try ;)

**Comment by pmjones** [comment]
@jelofson Super helpful. Your examples are, shall we say, contemporary. ;-)

**Comment by pmjones** [comment]
@jelofson I have added a new PersistTest class to cover the "all new" scenario (the only previously existing test), plus three new ones for updating many-to-one, one-to-many, and one-to-one. Doesn't cover all your above cases but it's a start.

**Comment by pmjones** [comment]
@jelofson As to why the last two examples of one-to-one in https://github.com/atlasphp/Atlas.Orm/issues/55#issuecomment-305873519 don't work, I'm not sure. Is it possible that both profile and user are defined as one-to-one on each other, instead of "user one-to-one (i.e. has-one) profile" and "profile many-to-one (i.e. belongs-to) user"?

**Comment by jelofson** [comment]
@pmjones Interesting. Setting the profile to a manyToOne, and the user as a oneToOne seems to work in both cases. Is that the proper set up for this scenario? So, it shouldn't be oneToOne in both cases? A manyToOne is just a "belongsTo" regardless of the other side's definition? 

Off to look at the tests...maybe...It's a hell of a nice evening out, and I think I may sit on my deck a while and enjoy ;)

**Comment by pmjones** [comment]
> It's a hell of a nice evening out, and I think I may sit on my deck a while and enjoy ;)

I forbid you from working on code any more tonight. Have a drink and enjoy the outside. :-)

**Comment by pmjones** [comment]
@jelofson OK BACK TO WORK

> A manyToOne is just a "belongsTo" regardless of the other side's definition?

Yes, that's right. In cases where you intend only one record (not many) to ever belong to a owning record the phrase "manyToOne" is jarring, but that is the way the foreign keys and joins end up working at the SQL level: they allow for many, even if you only intend one. (Well, at least when you don't have unique constraints, etc.)

Maybe what's needed here is to have *both* relationship names (manyToOne) *and* association names (belongsTo) available in the interface, so that it "looks" right when you put the records together.

In any case, let me know if that helps, and if it resolves the last of your woes.

**Comment by jelofson** [comment]
@pmjones Yes, I think that resolves it. I am going to try mucking around with it over the next few days using real-world data and see how it all goes. If I get confused or I can't get something to work properly, I will let you know. Thanks, and yes, back to work :)

**Comment by pmjones** [comment]
Right on. In that case, I am going to (1) merge #57, and (2) close this issue as a result. If new troubles appear, let me know. And seriously, thanks a ton for bringing this up; it's been a "think about doing this" item for a long time.
