### ISSUE TITLE
SQL Error on ManyToMany

### ISSUE THREAD

**Issue by jelofson** [atlasphp/Atlas.Orm#58]
Using the scenario of threads, tags, and taggings, and we try the following:

```php
$post = $atlas->fetchRecord(ThreadMapper::CLASS, 2, ['taggings', 'tags']);
```

If there are no associated tags for the post, then the query will fail (in mysql). Works in sqlite, so tests seem to pass.

What appears to happen is the 3rd query that is prepared will look something like this:
```
SELECT
    `tags`.`tag_id`,
    `tags`.`tag`
FROM
    `tags`
WHERE
    `tags`.`tag_id` IN ()
```
and MySQL will throw a syntax error (NOTE that sqlite does not return an error here)
```
PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 7 in /home/jelofson/www/atlas/vendor/aura/sql/src/ExtendedPdo.php:748
```
Perhaps the query for tags should be issued, given that there are no taggings returned.

**Comment by pmjones** [comment]
@jelofson Check out the `issue-58` branch and see if that solves this problem.

**Comment by jelofson** [comment]
@pmjones On my initial test, that looks like it's fixed. Thanks!

**Comment by pmjones** [comment]
Sweet. Merging now.
