### ISSUE TITLE
Question : Turn on Profiler 

### ISSUE THREAD

**Issue by harikt** [atlasphp/Atlas.Orm#6]
Hi Paul, 

Thank you for your good work.

I was wondering is there a way to turn on the profiler of ExtendedPdo . From the AtlasContainer it looks the ExtendedPdo is instantiated there.

Is there a way to view the query executed some how other than via the ExtendedPdo profiler ?

Thank you.

**Comment by pmjones** [comment]
Good question, and something I had not considered. It can be done but it's ugly. You have to go through the Mapper to the Table to get the underlying connection. E.g.:

``` php
$conn = $atlas->getMapper(Mapper::CLASS)->getTable()->getReadConnection();
$conn->setProfiler(...);
$conn->getProfiler()->setActive(true);
// ...
$conn->getProfiler()->setActive(false);
```

That should probably be made easier. :-/

**Comment by harikt** [comment]
I found another way. But still not satisfied.

This piece of code is written on `AtlasContainer` and probably we can add a function `turnOnProfiler()` which can set the profiler and make the connection active . Some constraints apply here for the correct functionality though.

```
    protected function setConnectionLocator(array $args)
    {
        $this->connectionLocator = new ConnectionLocator();
        $this->connectionLocator->setDefault(function () use ($args) {
            $pdo = new ExtendedPdo(...$args);
            $pdo->setProfiler($this->getProfiler());
            $pdo->getProfiler()->setActive(true);
            return $pdo;
        });
    }

    public function getProfiler()
    {
        if (! $this->profiler) {
            $this->profiler = new Profiler();
        }
        return $this->profiler;
    }
```

Update : 

It looks don't need to hack on this, it can be added via calling `getConnectionLocator()`  and `getDefault()` connection on Locator and then setting the profiler and turning on.

**Comment by pmjones** [comment]
> It looks don't need to hack on this, it can be added via calling getConnectionLocator() and getDefault() connection on Locator and then setting the profiler and turning on.

I'm taking this to mean that the issue can be closed; let me know if I'm wrong about that. :-)

**Comment by harikt** [comment]
I *wished* if there is an easy way to turn on / off profiler.
