### ISSUE TITLE
Persisting the manyToMany after the native record

### ISSUE THREAD

**Issue by jelofson** [atlasphp/Atlas.Orm#60]
When I append a new "taggings" to a post, should the post's "tags" also be updated?

```php
$post = $this->atlas->fetchRecord(PostsMapper::class, 1, ['postsTags', 'tags']);
$tag = $this->atlas->fetchRecord(TagsMapper::class, 3);
// There are no tags or posts_tags at this point
$post->tags = $this->atlas->newRecordSet(TagsMapper::class);
$postsTags = $this->atlas->newRecordSet(PostsTagsMapper::class);
$postsTags->appendNew([
    'post'=>$post,
    'tag'=>$tag
]);
        
$post->postsTags = $postsTags;

var_dump($this->atlas->persist($post));
// This foreach will not list the newly added tag unless you forcibly assign $post->tags[] = $tag
foreach ($post->tags as $t) {
    echo $t->tag;
}
```
The `$post->postsTags` is accurate, of course. I have no problem accessing the tags data this way, but should the tags recordset also be updated after persisting the native record? This does get back to the idea of discouraging the direct access to the manyToMany in favour of the oneToMany etc.

Thoughts?

**Comment by pmjones** [comment]
This is where I start having a little trouble. How much management of the "far" side of a many-to-many should the "through" be doing? (And vice versa.) It's hard to tell, automatically and reliably, if/when records should be added or removed, and to which element. If a tag is missing on the postsTags but present in tags, does that mean "add to postsTags" or does it mean "remove from tags" ?  Etc etc.

Currently, per #56 , if you are fetching with a many-to-many, I think that you'll have to deal with managing both the "through" and the "far side" manually. In that case, adding a tag means adding it in two places: on the through, *and* on the far side.

Likewise, if you are only fetching the "through" and then fetching *that* with the related many, you only need to update the one relationship, and then it automatically shows up.

(Hope that all makes sense; let me know if I need to clarify.)

**Comment by jelofson** [comment]
@pmjones I hear you. I am starting to really see the benefit of relying on the through rather than the far side as discussed in #56 . So, given that, I see this as more of a documentation thing, which I would like to help with. After all this testing, I will have a much better understanding of how it all works. 
What say we close this, and address it via docs when feasible? Fair enough?

BTW, thanks for entertaining all the "issues". I don't mean to fill up the issue box or anything, but I probably will ;)

**Comment by pmjones** [comment]
> What say we close this, and address it via docs when feasible?

I like this, and I very very VERY much look forward to your documentation assistance. Your work on the Solar docs was outstanding.

> thanks for entertaining all the "issues".

They're good questions and I'm glad to entertain them. Keep 'em coming, and close this issue at will.
