### ISSUE TITLE
Thoughts on returning an empty RecordSet vs empty array

### ISSUE THREAD

**Issue by jelofson** [atlasphp/Atlas.Orm#61]
This is really just about me being a bit lazy, but I have run into this a couple of times where returning an empty RecordSet might be beneficial.

Case 1 - appending a related

```php
$post = $atlas->fetchRecord(PostsMapper::class, 2, ['taggings', 'tags']);
$tag = $atlas->fetchRecord(TagsMapper::class, 3); // or it could be a new one

// There are no post->taggings in the DB yet.

// You must create a new recordset before appending because $post->taggings = []
if (! $post->taggings) {
    $post->taggings = $atlas->newRecordSet(TaggingsMapper::CLASS);
}
$post->taggings->appendNew([
    'post'=>$post,
    'tag'=>$tag
]);
```

Case 2 - Custom methods on the RecordSet object

```php
$authors = $atlas->select(AuthorsMapper::CLASS)->fetchRecordSet();
// You have a custom method in the AuthorsRecordSet class that does something.
// If there are no authors yet, then you need to create a new record set
if (! $authors) {
    $authors = $atlas->newRecordSet(AuthorsMapper::CLASS);
}
$foo = $authors->myMethod();
```

If `fetchRecordSet()` always returned a record set, even if empty, then you wouldn't need that additional check etc. 

What do you think? I am not opposed to the empty array, but it does mean a couple of extra steps on occasion.

**Comment by pmjones** [comment]
So, I can't change the existing behavior without causing a BC break.

However!

I can imagine adding a relationship method that forces the relationship to create a Record or RecordSet when there are no matches found. E.g.:

```php
$this->oneToOne('foo', FooMapper::CLASS)->useRecordWhenEmpty();
$this->oneToMany('bars', BarMapper::CLASS)->useRecordSetWhenEmpty();
```

I am not enamored of those method names, but you get the point.

Thoughts?

**Comment by jelofson** [comment]
That would certainly work for the relationships (case 1), but not for case 2. I only suggest it because it would be convenient. Maybe it's something to keep on the back burner for a bit and see how often it actually occurs. If it comes to a "man, I am tired of creating those recordsets all the time", then the juice may be worth the squeeze. Sound fair?

**Comment by pmjones** [comment]
Ah, I glazed over case 2, sorry.

Again, I can't change fetchRecordSet() at this without breaking BC, which I am loathe to do. But a similar solution might be applied; e.g., add fetchOrCreateRecordSet() to use instead of fetchRecordSet(). (I might say fetchRecordSet(true) to create one if there's no matches, but boolean flags of that sort rub me the wrong way.)

Further thoughts?

**Comment by pmjones** [comment]
Of course, I could just bite the bullet and say "there is a BC break in this minor release" but I think that's bad form.

**Comment by jelofson** [comment]
No no, BC = bad. Let's just keep it in mind for a v2 release down the road. That gives us time to ruminate on it for a while.

**Comment by pmjones** [comment]
Thinking out loud: perhaps the added methods might be:

```php
$mapper->forceRecord();
$mapper->forceRecordSet();
$mapperSelect->forceRecord();
$mapperSelect->forceRecordSet();
$relatedToOne->forceRecord();
$relatedToMany->forceRecordSet();
```

... to indicate that you *will* get a Record or RecordSet back, no matter what.

**Comment by pmjones** [comment]
@jelofson "Keep in mind for v2" -- All righty then.

In the mean time, forcing on the related is completely do-able with the added relationship method. Do you feel that would be a worthwhile addition?

**Comment by jelofson** [comment]
Not yet. I think that would introduce inconsistency. Hold off for now.

**Comment by pmjones** [comment]
Good enough! Close this as you see fit.

**Comment by harikt** [comment]
I think adding something like https://github.com/atlasphp/Atlas.Orm/issues/61#issuecomment-306894664 will not hurt. Yes I agree if v2 is releasing soon, and for that if `fetchRecord` changing to return empty records, then holding this may be right, else adding something like `fetchOrCreateRecordSet` make sense.

> NB I am more for `fetchOrCreate` than `force`. But I don't have a very strong opinion.

**Comment by pmjones** [comment]
@harikt I think at the Mapper level itself, leaving things as they are is reasonable until a v2. However, for the relationships, I think it might be OK to add a relationship definition method that creates a new Record or RecordSet if the related is not found. Cf. https://github.com/atlasphp/Atlas.Orm/issues/61#issuecomment-306890282 above.
