### ISSUE TITLE
$atlas->select()->cols()->fetchRecord() throws exception when you don't include the primary key col

### ISSUE THREAD

**Issue by jelofson** [atlasphp/Atlas.Orm#66]
The following will throw an exception because cols does not include `post_id`.

```php
// Only want the title col
$post = $atlas->select(PostsMapper::class)
    ->where('post_id = ?', 3)
    ->cols(['title', 'summary'])
    ->fetchRecord();
```
You should be able to fetch rows without including the primary key. Is there another way to calculate the identity key for the map?

Stack:

```
Atlas\Orm\Exception: Expected scalar value for primary key &#039;post_id&#039;, got array instead. in /home/jelofson/www/atlas/vendor/atlas/orm/src/Exception.php:243
Stack trace:
#0 /home/jelofson/www/atlas/vendor/atlas/orm/src/Table/AbstractTable.php(700): Atlas\Orm\Exception::primaryValueNotScalar(&#039;post_id&#039;, Array)
#1 /home/jelofson/www/atlas/vendor/atlas/orm/src/Table/AbstractTable.php(560): Atlas\Orm\Table\AbstractTable-&gt;calcIdentity(Array)
#2 /home/jelofson/www/atlas/vendor/atlas/orm/src/Table/TableSelect.php(309): Atlas\Orm\Table\AbstractTable-&gt;getSelectedRow(Array)
#3 [internal function]: Atlas\Orm\Table\TableSelect-&gt;fetchRow()
#4 /home/jelofson/www/atlas/vendor/atlas/orm/src/Mapper/MapperSelect.php(98): call_user_func_array(Array, Array)
#5 /home/jelofson/www/atlas/vendor/atlas/orm/src/Mapper/MapperSelect.php(217): Atlas\Orm\Mapper\MapperSelect-&gt;__call(&#039;fetchRow&#039;, Array)
#6 /home/jelofson/www/atlas/src/Blog/Controllers/Posts.php(28): Atlas\Orm\Mapper\MapperSelect-&gt;fetchRecord()
...
```

**Comment by pmjones** [comment]
Do you actually want a full Record object here? The entirety of Aura.Sql ExtendedPdo `fetch*()` and `yield*()` methods is available; e.g., you can use `fetchOne()` to get back `['title' => ..., 'summary' => ...]`.

This explains a bit more: https://github.com/atlasphp/Atlas.Orm/blob/1.x/docs/direct.md

**Comment by jelofson** [comment]
I can definitely do that. No problem there. I just didn't expect to get an exception simply because I was calling fetchRecord but didn't have the primary key. If I did want a record, for example, if I wanted to call some Record methods, then I would just have to make sure the primary key is included. 

Would you consider that something that will need addressing or something that should simply be documented?

**Comment by harikt** [comment]
I think documenting it may be good ( I guess it is a rare case ) . Else what will happen if someone tries to update the record ? It is partial data after all.

**Comment by jelofson** [comment]
I was going to close this, but I don't think I have written any docs about it yet. If it's no trouble, I will leave it open as a reminder to myself.

**Comment by pmjones** [comment]
I think the docs for this have been written and are live at http://atlasphp.io/mapper/2.x/reading.html#1-1-3-1

Thanks @jelofson for doing so!

**Comment by jelofson** [comment]
Oh man. Sorry for leaving that open for so long. Thanks for closing.

**Comment by pmjones** [comment]
Not at all, sir. :-)
