### ISSUE TITLE
Increase Priority of Domain Example in TODO

### ISSUE THREAD

**Issue by jakejohns** [atlasphp/Atlas.Orm#7]
I see in TODO listed under "Unknown Priority".

> Add examples on how to properly wrap a Record in the Domain.

This is my official request to increase that priority. :-)

Having even an incomplete or very-subject-to-change write up on best practices/intended-usage/big-picture stuff I think would make it easier to contribute and identify or solve problems.

**Comment by pmjones** [comment]
@jakejohns @harikt @limp @jblotus Your wish has been granted!

https://github.com/atlasphp/Atlas.Orm/blob/1.x/docs/domain.md

**Comment by harikt** [comment]
Thank you @pmjones for taking your time to write about this.
