### ISSUE TITLE
Wrong parameter in AbstractTable::insertRowPerform() for lastInsertId method at PostgreSQL

### ISSUE THREAD

**Issue by froschdesign** [atlasphp/Atlas.Orm#71]
At a PostgreSQL database the name of a sequence object is required for `PDO::lastInsertId`. At the moment the name of the autoincrement column is used.

https://github.com/atlasphp/Atlas.Orm/blob/bf4d2de4761d5299df7b00a0e92e9b64a6dcfd20/src/Table/AbstractTable.php#L363-L366

Changing the `getAutoinc` method in the specific table class doesn't work, because the method `AbstractTable::insertRowPrepare()` needs the name of the autoincrement column.

https://github.com/atlasphp/Atlas.Orm/blob/bf4d2de4761d5299df7b00a0e92e9b64a6dcfd20/src/Table/AbstractTable.php#L329-L332

**Comment by pmjones** [comment]
To make sure I understand: are you saying you need a sequence name *other than* the autoincrement column?

**Comment by froschdesign** [comment]
@pmjones 
> are you saying you need a sequence name other than the autoincrement column?

Right, the name of a sequence. (http://php.net/manual/en/pdo.lastinsertid.php#refsect1-pdo.lastinsertid-description)

My current workaround in the mapper:

```php
if ($record->getRow()->getStatus() === Row::INSERTED) {
    /** @var \Aura\Sql\ExtendedPdoInterface $connection */
    $connection = $this->getTable()->getWriteConnection();
    $lastId     = $connection->lastInsertId('foobar_id_seq');
}
```

(Thanks for the quick response!)

**Comment by pmjones** [comment]
I could have sworn I had something like that workaround implemented in the Insert object(s) for Postgres. Let me take a look around. Sorry for the hassle.

**Comment by pmjones** [comment]
Turns out what I have is in Aura.SqlQuery, and it's for extended Postgres tables, not non-extended ones. Working on a fix now. Thanks for your patience.

**Comment by pmjones** [comment]
Update: I *did* implement it in Aura.SqlQuery:

https://github.com/auraphp/Aura.SqlQuery/blob/3.x/src/Pgsql/Insert.php#L47-L54

But Atlas doesn't call getLastInsertIdName, it just presumes the name is the column name. Continuing to work on it.

**Comment by pmjones** [comment]
@froschdesign Do me a favor? In your local copy of `Atlas\Orm\Table\AbstractTable::insertRowPerform()` change from this:

```
        if ($autoinc) {
            $row->$autoinc = $connection->lastInsertId($autoinc);
        }
```

To this:

```
        $autoinc = $this->getAutoinc();
        if ($autoinc) {
            $lastInsertIdName = $insert->getLastInsertIdName($autoinc);
            $row->$autoinc = $connection->lastInsertId($lastInsertIdName);
        }
```

And tell me if it works for you.

**Comment by pmjones** [comment]
@froschdesign see also #72 as a fix

**Comment by froschdesign** [comment]
@pmjones 
Sorry for the late response.

> And tell me if it works for you.

Works like a charm! 👍

**Comment by pmjones** [comment]
Excellent! I have applied the fix on the 1.x branch; use that, until the next release comes out (which I hope to do later today).

**Comment by froschdesign** [comment]
Great! Thank you.
