### ISSUE TITLE
Add a link back to github in the docs

### ISSUE THREAD

**Issue by jelofson** [atlasphp/Atlas.Orm#73]
This might be handy

**Comment by pmjones** [comment]
Good call. You want to send a PR on whatever doc page you think is appropriate?

**Comment by jelofson** [comment]
Yup. No prob

**Comment by jelofson** [comment]
@pmjones Wondering how hard it is to modify the template for the "landing" page?
http://atlasphp.io/

Might be nice to have a "What is" for both the mapper and the cli on that landing page, including a link back to github. What do you think? I am not super familiar with bookdown, but I think it should be doable.

Thoughts?

**Comment by pmjones** [comment]
> how hard it is to modify the template for the "landing" page?

Right now, straightforward but not automated. One proposed (by me!) feature for Bookdown is "custom home page" and/or "custom prepend/append on TOC pages". Either of those would work, but neither has been implemented.

/me ponders

It should be possible, in the atlasphp.io repo, to modify the "build" shell script to prepend (or insert at an appropriate location) any home page content we might like, but that will require some effort and attention.

**Comment by jelofson** [comment]
I think for now, I will probably just slap a link...somewhere...Maybe an about page for the mapper and cli similar to the readme at each repo.

**Comment by pmjones** [comment]
This has been complete for quite a while now; links are on the landing page.
