### ISSUE TITLE
Ordering on a many-to-many

### ISSUE THREAD

**Issue by jelofson** [atlasphp/Atlas.Orm#76]
So, it is possible to modify the select via a closure when returning related records.

For example:
```php
<?php
// fetch thread_id 1; with only the last 10 related replies in descending order;
// including each reply author
$threadRecord = $atlas->fetchRecord(
    ThreadMapper::CLASS,
    '1',
    [
        'author',
        'summary',
        'replies' => function ($selectReplies) {
            $selectReplies
                ->limit(10)
                ->orderBy(['reply_id DESC'])
                ->with([
                    'author'
                ]);
        },
    ]
);
```
However, when you have a many-to-many through an association, any ordering on the many-to-may is ignored. This is because the stitching loops through the association records first, performs a "match" and then adds the foreign records. 

Consider this fetch:

```php
<?php
$author = $this->atlas->fetchRecord(AuthorsMapper::class, $id, [
            'author_publications',
            'publications'=>function ($select) {
                $select->orderBy(['title ASC']);
            }
        ]);
```

My suggestion, and I tested this a bit, is to loop through the foreign records first, and then check those against the through records. See below from ManyToMany.php

```php
<?php
    protected function getMatches(RecordInterface $nativeRecord, array $foreignRecords)
    {
        $matches = [];

        /* Don't loop through association first.
        foreach ($nativeRecord->{$this->throughName} as $throughRecord) {
            foreach ($foreignRecords as $foreignRecord) {
                if ($this->recordsMatch($throughRecord, $foreignRecord)) {
                    $matches[] = $foreignRecord;
                }
            }
        }
         * 
         */
        // Loop through the foreigns and append to matches in the order they are already in.
        foreach ($foreignRecords as $foreignRecord) {
            foreach ($nativeRecord->{$this->throughName} as $throughRecord) {
                if ($this->recordsMatch($throughRecord, $foreignRecord)) {
                    $matches[] = $foreignRecord;
                }
            }
        }
        return $matches;
    }
```

What do you think?

**Comment by pmjones** [comment]
> any ordering on the many-to-may is ignored

Well, rats.

> What do you think?

I have no problem with that.

As a followup, I wonder if this is Yet Another Reason to de-emphasize the use of "direct" many-to-many, in favor of "indirect" many-to-many using the "through" relationship. That is, make your first example the promoted one, and the second example the deprecated one.

**Comment by pmjones** [comment]
In fact, if we're going to make the change, might be good to make it in both 1.x and 2.x.

**Comment by pmjones** [comment]
Another followup: if the order is honored on the many-to-many, does that mean the order is then *not* honored on the "through" association?

**Comment by jelofson** [comment]
> Another followup: if the order is honored on the many-to-many, does that mean the order is then not honored on the "through" association?

The through association is not affected. They are stitched into the native record independently. 
```php
<?php
$author = $this->atlas->fetchRecord(AuthorsMapper::class, $id, [
    'author_publications'=>function ($select) {
        $select=>orderBy(['author_id DESC']);
    },
    'publications'=>function ($select) {
        $select->orderBy(['title ASC']);
    }
]);

```
When looping through `$author->author_publications`, the order of author_publications is as expected. 

I see value in emphasizing the through association, however, ordering the "far side", in this case publications, is one of the few times direct access to the far side helps. 

Otherwise, you probably have to perform a join and a with? Or a joinWith? I haven't tried any joinWith() yet.

**Comment by pmjones** [comment]
> Otherwise, you probably have to perform a join and a with? Or a joinWith? I haven't tried any joinWith() yet.

Probably.

OK, tell you what: send a PR for 1.x and 2.x with your proposed change, and I'll merge them.

Thanks for the attention to detail here.

**Comment by pmjones** [comment]
@jelofson I got impatient (my fault not yours :-) -- take a look at #77 when you have time.

**Comment by jelofson** [comment]
@pmjones Looks good to me. Thanks.

**Comment by pmjones** [comment]
Good deal; I will backport to 1.x as well. Thanks for your work here.
