### ISSUE TITLE
Question: Where is the best place to convert php values to database values?

### ISSUE THREAD

**Issue by fadoe** [atlasphp/Atlas.Orm#90]
In my application I work with UUIDs. In the database table this values are saved as binary(16). In doctrine I can write a custom field type like this:

```
namespace Infrastructure\Persistence\Doctrine\Type;

use Doctrine\DBAL\Platforms\AbstractPlatform;
use Doctrine\DBAL\Types\StringType;
use Domain\Station\Model\StationId;
use Ramsey\Uuid\Uuid;

class StationIdType extends StringType
{
    public function convertToPHPValue($value, AbstractPlatform $platform): ?StationId
    {
        return $value ? StationId::fromString(Uuid::fromBytes($value)->toString()) : null;
    }

    public function convertToDatabaseValue($value, AbstractPlatform $platform): ?string
    {
        return $value instanceof StationId ? Uuid::fromString((string) $value)->getBytes() : null;
    }

    public function getName(): string
    {
        return 'station_id';
    }
}
```
Where is the best place to add this in atlas php?

**Comment by sunkan** [comment]
Hi

Have you had a look at https://github.com/atlasphp/Atlas.Orm/blob/2.x/docs/events.md

You could use the table events to turn the data to binary before update/Insert and then on select turn them back into string

**Comment by pmjones** [comment]
@fadoe does @sunkan's answer help you out?

**Comment by fadoe** [comment]
I test it with

```php
class StationTableEvents extends TableEvents
{
    public function modifySelectedRow(TableInterface $table, RowInterface $row): void
    {
        $id = $row->id;

        $value = $this->convertToPHPValue($id);
        $row->id = $value;
    }

    private function convertToPHPValue($value): ?StationId
    {
        return $value ? StationId::fromString(Uuid::fromBytes($value)->toString()) : null;
    }

    private function convertToDatabaseValue($value): ?string
    {
        return $value instanceof StationId ? Uuid::fromString((string) $value)->getBytes() : null;
    }
}
```
But now i get this exception trace:

```
Exception trace:
 Atlas\Orm\Exception::invalidType() at /home/falk/Projekte/Applications/playlistgrabber/vendor/atlas/orm/src/Table/Row.php:323
 Atlas\Orm\Table\Row->assertValid() at /home/falk/Projekte/Applications/playlistgrabber/vendor/atlas/orm/src/Table/Row.php:297
 Atlas\Orm\Table\Row->modify() at /home/falk/Projekte/Applications/playlistgrabber/vendor/atlas/orm/src/Table/Row.php:122
 Atlas\Orm\Table\Row->__set() at /home/falk/Projekte/Applications/playlistgrabber/src/PlaylistGrabber/src/Infrastructure/Persistence/AtlasOrm/Station/StationTableEvents.php:25
 FaDoe\PlaylistGrabber\Infrastructure\Persistence\AtlasOrm\Station\StationTableEvents->modifySelectedRow() at /home/falk/Projekte/Applications/playlistgrabber/vendor/atlas/orm/src/Table/AbstractTable.php:544
 Atlas\Orm\Table\AbstractTable->getSelectedRow() at /home/falk/Projekte/Applications/playlistgrabber/vendor/atlas/orm/src/Table/TableSelect.php:330
 Atlas\Orm\Table\TableSelect->fetchRows() at n/a:n/a
 call_user_func_array() at /home/falk/Projekte/Applications/playlistgrabber/vendor/atlas/orm/src/Mapper/MapperSelect.php:127
 Atlas\Orm\Mapper\MapperSelect->__call() at /home/falk/Projekte/Applications/playlistgrabber/vendor/atlas/orm/src/Mapper/MapperSelect.php:263
 Atlas\Orm\Mapper\MapperSelect->fetchRecords() at /home/falk/Projekte/Applications/playlistgrabber/src/PlaylistGrabber/src/Infrastructure/Station/Repository/AtlasOrmStationRepository.php:42
...
```

So I think the best place to do this cast is in the repository after fetching the data. Or to write a entity that can handle the binary version for the ORM and the ValueObject version for the application.

**Comment by pmjones** [comment]
@fadoe Ah so! Yes, casting at the Domain level is probably the right thing to do in this case; I did not realize that you were trying to store an object in the Row.

FWIW, remember that Atlas is intended to model the persistence layer, not the domain layer. With that design constraint in mind, I wrote the Row::assertValidValue() method to make sure that only scalars and nulls could be set as values on a row, since scalars and nulls are the only things that move back and forth between PHP and the database. As such, the "right" place to create objects from Row values is in the domain layer.

However, I have lately begun to think that validation approach is a little too restrictive; in a future version of Atlas I expect to relax or remove it. Relaxing it in 2.x *might* be possible without breaking BC (and expectations) but I am not sure at this point.

Sorry for the hassle, and let me know if we can close this issue for now.

**Comment by fadoe** [comment]
@pmjones I played around and Atlas is a very good ORM. Not so bloated like doctrine. Thank you for this great work!
I think you should not remove the strict validation. Programs should validate the input/output.

Thanks again. I close this question.

**Comment by pmjones** [comment]
Thanks for saying so @fadoe :-)
