### ISSUE TITLE
Issue with character encoding

### ISSUE THREAD

**Issue by steffdimitrov** [atlasphp/Atlas.Orm#96]
Hello, I think there is a bug with fetching records with character encoding different that UTF-8.

Package version:
```bash
atlas/cli                1.1.0
atlas/orm             2.5.0
aura/cli                2.2.0
aura/sql               2.6.0
aura/sqlquery      2.7.1
aura/sqlschema   2.0.3
```

In database I have record like this: "Bayern München"
When I use native PDO query the result is the same, but when I query it through orm I get this: Bayern M�nchen

My table schema is:
```sql
CREATE TABLE `teams_i18n` (
  `title` varchar(255) CHARACTER SET latin1 NOT NULL
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;
```

**Comment by froschdesign** [comment]
@steffdimitrov 
Which character set do you set in the [DSN](http://php.net/manual/en/ref.pdo-mysql.connection.php)?

**Comment by steffdimitrov** [comment]
In my DSN I have: SET NAMES 'utf8' COLLATE 'utf8_unicode_ci'

**Comment by froschdesign** [comment]
You don't need `SET NAMES`. The following is enough:
```php
use Atlas\Orm\Atlas;

$atlas = Atlas::new(
    'mysql:host=localhost;dbname=testdb;charset=utf8',
    'username',
    'password'
);
```
---

> `title varchar(255) CHARACTER SET latin1 NOT NULL`

Why `latin1` here? _A bit strange._

**Comment by steffdimitrov** [comment]
I agree with all stuffs about character encoding but currently in my project I have two frameworks (don't ask why) - I have CodeIgniter and Atlas for ORM. When I get data with CI orm the data is correct with currently character encoding, when I fetch it with Atlas it's not. CI uses mysqli driver, and has the same `SET...` stuff.

**Comment by froschdesign** [comment]
I can not reproduce your problem.

composer.json:
```json
"require": {
    "atlas/orm": "2.6.0",
    "atlas/cli": "1.1.0"
},
```
Test script:
```php
$atlasContainer = new \Atlas\Orm\AtlasContainer(
    'mysql:host=localhost;dbname=soccer;charset=utf8',
    'username',
    'password'
);

$atlasContainer->setMappers(
    [
        \Teams\TeamsMapper::CLASS,
    ]
);

$atlas     = $atlasContainer->getAtlas();
$recordSet = $atlas->select(\Teams\TeamsMapper::class)->fetchRecordSet();

var_dump($recordSet->getArrayCopy());
```
Result:
```
array(2) {
  [0] =>
  array(1) {
    'tite' =>
    string(18) "FC Bayern München"
  }
  [1] =>
  array(1) {
    'tite' =>
    string(9) "HFC Halle"
  }
}
```
(Same results for version 2.5.0 and 2.6.0 of Atlas.ORM)

**Comment by harikt** [comment]
>   `title` varchar(255) CHARACTER SET latin1 NOT NULL

I think @froschdesign mentioned this. You should change this character set. It should not be Latin.

**Comment by kevinsmith** [comment]
@steffdimitrov Is the CI ORM using a `latin1` connection charset, by chance?

**Comment by harikt** [comment]
@kevinsmith your question actually make me look at travis and seem there is no configuration for atlas to run tests. or am I missing something ?

**Comment by kevinsmith** [comment]
@harikt I'm not sure about the continuous integration setup for Atlas, I was referring to @steffdimitrov's CodeIgniter configuration.

**Comment by harikt** [comment]
I misunderstood seeing CI.

**Comment by kevinsmith** [comment]
@harikt No worries!

**Comment by steffdimitrov** [comment]
@kevinsmith no, it uses utf8.

**Comment by steffdimitrov** [comment]
Ok, you can close issue - it was my mistake.
