### ISSUE TITLE
Relationships manyToOne NULL

### ISSUE THREAD

**Issue by ElGigi** [atlasphp/Atlas.Orm#97]
Hi,

I have a problem with relationships manyToOne with capacity to be null.

The relation key return FALSE if the relation is NULL. I can understand that.
But the problem, it's with Atlas.Transit, the Transit object throw an exception.

For example :

Entities:
- class Thread
- class Author

Thread can have an author or anonymous (without author).
In the case of anonymous. The field "author" is FALSE instead NULL.
Atlas.Transit works fine with existent relation, but throw an exception if relation is NULL:
```
TypeError: Argument 2 passed to Atlas\Transit\Transit::newDomainEntity() must be an instance of Atlas\Mapper\Record, boolean given
```

Thanks.

**Comment by ElGigi** [comment]
The same problem for oneToOne relationship.

A track for resolution?

```php
class OneToOne extends DeletableRelationship
{
    protected function stitchIntoRecord(
        Record $nativeRecord,
        array $foreignRecords
    ) : void {
        $nativeRecord->{$this->name} = false;
        if ($this->onDelete === static::SET_NULL) {
            $nativeRecord->{$this->name} = null;
        }

        foreach ($foreignRecords as $foreignRecord) {
            if ($this->recordsMatch($nativeRecord, $foreignRecord)) {
                $nativeRecord->{$this->name} = $foreignRecord;
            }
        }
    }

    // ...
}
```

So if reference column can be null, the value must not be false but null?

**Comment by pmjones** [comment]
/me ponders

Can you tell me a little about the domain object that is being built from the record?

**Comment by ElGigi** [comment]
Yes.

For example:
```php
class Author
{
    // ...

    public function __construct(?int $author_id, ?string $name)
    {
        $this->author_id = $author_id;
        // ...
    }
}

class Thread
{
    public function __construct(?int $article_id, ?string $title, ?string $content, ?Author $author)
    {
        $this->article_id = $article_id;
        // ...
    }
}
```

And the relationships in DataSource:
```php
class AuthorRelationships extends MapperRelationships
{
    protected function define()
    {
        $this->oneToMany('threads',
                         Thread::CLASS,
                         [
                             'author_id' => 'author_id',
                         ]);
    }
}

class ThreadRelationships extends MapperRelationships
{
    protected function define()
    {
        $this->manyToOne('author',
                        Author::CLASS,
                        [
                            'author_id' => 'author_id',
                        ])
             ->onDeleteSetNull();
    }
}
```

**Comment by pmjones** [comment]
And the problem is that sometimes, when you fetch a ThreadRecord from the data source with('author'), the author field is false because there is no related author row?

**Comment by ElGigi** [comment]
Yes is that.
If no author, for anonymous thread (for example), the field is false instead null.

**Comment by pmjones** [comment]
All right, I think I understand now.

Some background: the `false` is there to indicate that you tried to fetch a relationship, but there was nothing related (as vs `null` which means you never tried to fetch the relationship in the first place).

The most expedient solution I can think of is to modify Atlas Transit to accept both "false" and "null" to mean "null" when the target domain property is an object. Would that work for you here?

**Comment by ElGigi** [comment]
Yes of course, that will works for me if it's implemented in Transit.

**Comment by pmjones** [comment]
@ElGigi please examine https://github.com/atlasphp/Atlas.Transit/pull/7 and see if it works for you!
